# BWT - Deep Learning Track

## Broadcasting in numpy
### Adil Mubashir Chaudhry

Broadcasting allows NumPy to work with arrays of different shapes and sizes while performing arithmetic operations, without the need for explicit reshaping of the arrays. The smaller array is "broadcasted" across the larger array so that they have compatible shapes.

In [1]:
import numpy as np

In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
arr = arr*4
arr

array([ 0,  4,  8, 12, 16])

In [5]:
arr2 = np.random.randn(4, 3)
arr2.mean(0)

array([ 0.09816718,  1.46852822, -0.15405661])

In [6]:
arr2_updated = arr2 - arr2.mean(0)
arr2_updated

array([[-0.49948153, -1.09880509, -1.16517412],
       [ 0.59761231, -0.43524428,  1.56642462],
       [-0.60811301,  0.48002025, -0.0894933 ],
       [ 0.50998223,  1.05402912, -0.3117572 ]])

In [7]:
arr2_updated.mean(0)

array([ 0.00000000e+00, -1.66533454e-16, -2.77555756e-17])

In [9]:
row_means = arr2.mean(1)
row_means.shape

(4,)

In [10]:
row_means.reshape((4, 1))

array([[-0.45027398],
       [ 1.04714381],
       [ 0.39835091],
       [ 0.88829765]])

In [14]:
demeaned = arr2 - row_means.reshape((4, 1))
demeaned.mean(1)

array([-3.70074342e-17,  7.40148683e-17, -3.70074342e-17,  0.00000000e+00])

In [15]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([1, 2, 3])
z = x * y
z

array([[ 1,  4,  9],
       [ 4, 10, 18]])